DROP TABLE IF EXISTS USER;

CREATE TABLE USER (
      id INT AUTO_INCREMENT PRIMARY KEY,
      USER_ID VARCHAR(250) NOT NULL,
      PASSWORD VARCHAR(250) NOT NULL,
      NICKNAME VARCHAR(250) DEFAULT NULL,
      EMAIL VARCHAR(250) DEFAULT NULL,
      PHONE_NUMBER VARCHAR(250) DEFAULT NULL,
      BIRTH_DAY VARCHAR(250),
      GENDER INT DEFAULT 0,
      WRITE_PERMISSION INT DEFAULT 0
)