DROP TABLE IF EXISTS ARTICLE;
DROP TABLE IF EXISTS MAINPAGE;
DROP TABLE IF EXISTS CATEGORY;

CREATE TABLE ARTICLE (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  TYPE INT,
  TITLE VARCHAR(250) NOT NULL,
  SUB_TITLE VARCHAR(250) DEFAULT NULL,
  THUMBNAIL VARCHAR(250) DEFAULT NULL,
  CONTENTS VARCHAR(10000) DEFAULT NULL,
  TAGS VARCHAR(250) DEFAULT NULL,
  CATEGORY_Id INT
);

CREATE TABLE MAINPAGE (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  ARTICLE_Id INT
);

CREATE TABLE CATEGORY (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  name VARCHAR(250) NOT NULL
);