DROP TABLE IF EXISTS ARTICLE;
DROP TABLE IF EXISTS MAINPAGE;
DROP TABLE IF EXISTS CATEGORY;

CREATE TABLE ARTICLE (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  type INT,
  title VARCHAR(250) NOT NULL,
  subTitle VARCHAR(250) DEFAULT NULL,
  thumbnail VARCHAR(250) DEFAULT NULL,
  contents VARCHAR(10000) DEFAULT NULL,
  tags VARCHAR(250) DEFAULT NULL,
  categoryId INT
);

CREATE TABLE MAINPAGE (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  articleId INT
);

CREATE TABLE CATEGORY (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  name VARCHAR(250) NOT NULL
);